# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "synergistic-equity-app"
client_id = "1d40468abbab667dabd1db83ad767d68"
application_url = "https://tin-racks-department-superintendent.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_customers"

[auth]
redirect_urls = [
  "https://tin-racks-department-superintendent.trycloudflare.com/auth/callback",
  "https://tin-racks-department-superintendent.trycloudflare.com/auth/shopify/callback",
  "https://tin-racks-department-superintendent.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "staging-master-store.myshopify.com"
